# Generated by Django 4.2.5 on 2023-09-17 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 8, 8, 21, 633191, tzinfo=datetime.timezone.utc)),
        ),
    ]
